apiVersion: edgeapplication.kubeedge/v1alpha1
kind: EdgeApplicationOverrider
metadata:
  labels:
    app.kubernetes.io/name: edgeapplicationoverrider
    app.kubernetes.io/instance: edgeapplicationoverrider-sample
    app.kubernetes.io/part-of: template
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: template
  name: edgeapplicationoverrider-sample
spec:
  # TODO(user): Add fields here
